---
title: '001401'  
description: '<small>&#8249; [All error codes](/errors/codes#refunds)</small>'
---
  
<table>
    <tbody>
        <tr>
            <th class="header"><strong>Error message</strong></th>
            <td class="table-content">Transaction has already been successfully refunded</td>
        </tr>
        <tr>
            <th class="header"><strong>Description</strong></th>
            <td class="table-content">The transaction has already been successfully refunded.</td>
        </tr>
        <tr>
            <th class="header"><strong>Categories</strong></th>
            <td class="table-content">  
<div class="label">Refund</div>
</td>
        </tr>
    </tbody>
</table>  

#### Causes  

This error occurs when attempting to make a Refund on a transaction that has already been refunded.  

#### Example  
```json API Response
{
    "Id":"328944496",
    "Tag":null,
    "CreationDate":1676552403,
    "AuthorId":"1244431803",
    "CreditedUserId":null,
    "DebitedFunds":{
        "Currency":"EUR",
        "Amount":1900
    },
    "CreditedFunds":{
        "Currency":"EUR",
        "Amount":1900
    },
    "Fees":{
        "Currency":"EUR",
        "Amount":0
    },
    "Status":"FAILED",
    "ResultCode":"001401",
    "ResultMessage":"Transaction has already been successfully refunded",
    "ExecutionDate":null,
    "Type":"TRANSFER",
    "Nature":"REFUND",
    "InitialTransactionId":"328444570",
    "InitialTransactionType":"TRANSFER",
    "InitialTransactionNature":"REGULAR",
    "DebitedWalletId":"154444418",
    "CreditedWalletId":"1233444806",
    "RefundReason":{
        "RefundReasonMessage":null,
        "RefundReasonType":"OTHER"
    }
}
```